language: node_js
deploy:
  provider: s3
  access_key_id: AKIAJNXQ7B5RTVBEXN6A
  secret_access_key: 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 
  bucket: snapscrip
  skip_cleanup: true
  local-dir: app
