language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
deploy:
  provider: s3
  access_key_id: S3_ACCESS_KEY 
  secret_access_key: S3_SECRET_KEY
  bucket: snapscrip
  skip_cleanup: true
  local-dir: app
