deploy:
  provider: s3
  access_key_id: YOUR AWS ACCESS KEY
  secret_access_key: YOUR AWS SECRET KEY
  bucket: S3 Bucket
  skip_cleanup: true
  local-dir: app
  upload-dir: snapscrip.com
vBBOYosUQuNIRy91YzeloHxiX6VxiddQzupk6qkK:
  secure: S7KbHKWmKEsoUCEImAfy5aLW9lXqTX6nqXkzLSsVLH4AW6BbfQfbShHZB/cw4tsBEQdQkXId/68beWfcdjUGEAIUPu2Ia7ydUDgIvGIi5KQSkfK8xhvLCYLKe1RnBPx29YMrdvktWK6aRjJAe922o7HX69BSjIAdUNWSvdcmP38=
